[package]
name = "util-core-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = [
  "rt",
  "rt-multi-thread",
  "time",
  "macros",
  "signal"
] }
tokio-util = "0.7"
